id: PCCFE935D
initial_creation_type: input
source_metadata:
  title: Bodhicaryāvatāra Series
  language: fr
  description: 'Lotsawa House presents the following texts as part of its Bodhicaryāvatāra
    Series:'
  volume:
    b5f9137e96e641a39ac3d31e8d836d94:
      title: 'Bodhicaryāvatāra—Chapter 1: The Benefits of Bodhicitta'
      parent: Bodhicaryāvatāra Root text
    f22ac9a32b9944449cee60b28954d6bb:
      title: 'Bodhicaryāvatāra—Chapter 2: Confession of Negativity'
      parent: Bodhicaryāvatāra Root text
    0e2d782a8be04147be99513af5d60893:
      title: 'Bodhicaryāvatāra—Chapter 3: Fully Adopting Bodhicitta'
      parent: Bodhicaryāvatāra Root text
    1e54587e24ba4e03b261e78f301c5769:
      title: 'Bodhicaryāvatāra: Teachings and Overview'
      parent: Commentaries
    dff8f15f28e2445cbe9acb196ef9e74b:
      title: Overview of the Bodhicaryāvatāra
      parent: Commentaries
    eec44dc00f194a2d99f8784c9068ec77:
      title: 'The Brightly Shining Sun: A Step-by-Step Guide to Meditating on the
        Bodhicaryāvatāra'
      parent: Commentaries
    8042920dfd414653a2bd4a413151d4d2:
      title: 'The Garland of Jewel Ornaments: The Stages of Meditating on the Bodhicaryāvatāra'
      parent: Commentaries
    bb0dff1606374173b24c6742c58a3ce1:
      title: Bodhicaryāvatāra Lineage Prayer
      parent: Lineage Prayers
    2d93e5f07b4647109dc74e46d6ce6e3c:
      title: Prayer to the Lineage of the Bodhicaryāvatāra
      parent: Lineage Prayers
    f9defff10baf467abe69167b2c02e49b:
      title: 'Vines of Amṛta: A Prayer to the Lineage of the Bodhicaryāvatāra'
      parent: Lineage Prayers
created_at: '2022-03-01T03:02:08.556693'
last_modified_at: '2022-03-01T03:02:08.556696'
